DROP ROLE IF EXISTS calendar_api_svc;
DROP ROLE IF EXISTS calendar_ldr_svc;

CREATE ROLE calendar_ldr_svc WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'ju8Cie0c';

CREATE ROLE calendar_api_svc WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'Yeishee4';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO calendar_ldr_svc;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO calendar_ldr_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO calendar_api_svc;
