DROP DATABASE IF EXISTS calendar;

DROP ROLE IF EXISTS calendar_api_svc;
DROP ROLE IF EXISTS calendar_ldr_svc;

CREATE ROLE calendar_ldr_svc WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'ju8Cie0c';

CREATE ROLE calendar_api_svc WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'Yeishee4';

CREATE DATABASE calendar
    WITH 
    OWNER = calendar_ldr_svc
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO calendar_api_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO calendar_api_svc;