INSERT INTO languages (code, name, native_name) VALUES ('id', 'Indonesian', 'Bahasa Indonesia');
INSERT INTO languages (code, name, native_name) VALUES ('th', 'Thai', 'ไทย');
INSERT INTO languages (code, name, native_name) VALUES ('vi', 'Vietnamese', 'Việtnam');
INSERT INTO languages (code, name, native_name) VALUES ('zh-hant', 'Chinese (Traditional)', '繁體中文');
INSERT INTO languages (code, name, native_name) VALUES ('zh-hans', 'Chinese (Simplified)', '简体中文');
INSERT INTO languages (code, name, native_name) VALUES ('kr', 'Korean', '한국어');
INSERT INTO languages (code, name, native_name) VALUES ('ja', 'Japanese', '日本語');
INSERT INTO languages (code, name, native_name) VALUES ('he', 'Hebrew', 'עברית');
INSERT INTO languages (code, name, native_name) VALUES ('fi', 'Finnish', 'Suomi');
INSERT INTO languages (code, name, native_name) VALUES ('sv', 'Swedish', 'Svenska');
INSERT INTO languages (code, name, native_name) VALUES ('el', 'Greek', 'Ελληνικά');
INSERT INTO languages (code, name, native_name) VALUES ('ar', 'Arabic', 'العربية');
INSERT INTO languages (code, name, native_name) VALUES ('ru', 'Russian', 'Русский');
INSERT INTO languages (code, name, native_name) VALUES ('pl', 'Polish', 'Polski');
INSERT INTO languages (code, name, native_name) VALUES ('pt', 'Portuguese', 'Português');
INSERT INTO languages (code, name, native_name) VALUES ('nl', 'Dutch', 'Nederlands');
INSERT INTO languages (code, name, native_name) VALUES ('it', 'Italian', 'Italiano');
INSERT INTO languages (code, name, native_name) VALUES ('fr', 'French', 'Français');
INSERT INTO languages (code, name, native_name) VALUES ('es', 'Spanish', 'Español');
INSERT INTO languages (code, name, native_name) VALUES ('de', 'German', 'Deutsch');
INSERT INTO languages (code, name, native_name) VALUES ('en', 'English', 'English');
INSERT INTO languages (code, name, native_name) VALUES ('ms', 'Malay', 'Bahasa Melayu');
INSERT INTO languages (code, name, native_name) VALUES ('tr', 'Turkish', 'Türkçe');
INSERT INTO languages (code, name, native_name) VALUES ('hi', 'Hindi', 'हिन्दी' );

INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AF', 'AS', 'AFN', null, 'Afghanistan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PG', 'OC', 'PGK', null, 'Papua New Guinea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PY', 'SA', 'PYG', null, 'Paraguay');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PE', 'SA', 'PEN', null, 'Peru');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PH', 'AS', 'PHP', null, 'Philippines');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PN', 'OC', 'NZD', null, 'Pitcairn Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PL', 'EU', 'PLN', null, 'Poland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PT', 'EU', 'EUR', null, 'Portugal');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PR', 'NA', 'USD', null, 'Puerto Rico');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('QA', 'AS', 'QAR', null, 'Qatar');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('RE', 'AF', 'EUR', null, 'Réunion');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('RO', 'EU', 'RON', null, 'Romania');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('RW', 'AF', 'RWF', null, 'Rwanda');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BL', 'NA', 'EUR', null, 'Saint Barthélemy');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KN', 'NA', 'XCD', null, 'Saint Kitts and Nevis');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LC', 'NA', 'XCD', null, 'Saint Lucia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MF', 'NA', 'EUR', null, 'Saint Martin');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PM', 'NA', 'EUR', null, 'Saint Pierre and Miquelon');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VC', 'NA', 'XCD', null, 'Saint Vincent and the Grenadines');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('WS', 'OC', 'WST', null, 'Samoa');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SM', 'EU', 'EUR', null, 'San Marino');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ST', 'AF', 'STN', null, 'Sao Tome and Principe');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SA', 'AS', 'SAR', null, 'Saudi Arabia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SN', 'AF', 'XOF', null, 'Senegal');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('RS', 'EU', 'RSD', null, 'Serbia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SC', 'AF', 'SCR', null, 'Seychelles');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SL', 'AF', 'SLL', null, 'Sierra Leone');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SG', 'AS', 'SGD', null, 'Singapore');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PA', 'NA', 'USD', null, 'Panama');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SI', 'EU', 'EUR', null, 'Slovenia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PS', 'AS', 'ILS', null, 'Palestinian Territory');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PK', 'AS', 'PKR', null, 'Pakistan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MR', 'AF', 'MRU', null, 'Mauritania');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MU', 'AF', 'MUR', null, 'Mauritius');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('YT', 'AF', 'EUR', null, 'Mayotte');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MX', 'NA', 'MXN', null, 'Mexico');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FM', 'OC', 'USD', null, 'Micronesia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MD', 'EU', 'MDL', null, 'Moldova');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MC', 'EU', 'EUR', null, 'Monaco');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MN', 'AS', 'MNT', null, 'Mongolia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ME', 'EU', 'EUR', null, 'Montenegro');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MS', 'NA', 'XCD', null, 'Montserrat');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MA', 'AF', 'MAD', null, 'Morocco');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MZ', 'AF', 'MZN', null, 'Mozambique');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MM', 'AS', 'MMK', null, 'Myanmar');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NR', 'OC', 'AUD', null, 'Nauru');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NP', 'AS', 'NPR', null, 'Nepal');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NL', 'EU', 'EUR', null, 'Netherlands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NC', 'OC', 'XPF', null, 'New Caledonia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NZ', 'OC', 'NZD', null, 'New Zealand');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NI', 'NA', 'NIO', null, 'Nicaragua');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NE', 'AF', 'XOF', null, 'Niger');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NG', 'AF', 'NGN', null, 'Nigeria');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NU', 'OC', 'NZD', null, 'Niue');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NF', 'OC', 'AUD', null, 'Norfolk Island');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MP', 'OC', 'USD', null, 'Northern Mariana Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MK', 'EU', 'MKD', null, 'North Macedonia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NO', 'EU', 'NOK', null, 'Norway');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('OM', 'AS', 'OMR', null, 'Oman');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PW', 'OC', 'USD', null, 'Palau');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SB', 'OC', 'SBD', null, 'Solomon Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SO', 'AF', 'SOS', null, 'Somalia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ZA', 'AF', 'ZAR', null, 'South Africa');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ZM', 'AF', 'ZMW', null, 'Zambia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ZW', 'AF', 'USD', null, 'Zimbabwe');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BN', 'AS', 'BND', null, 'Brunei Darussalam');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BQ', 'NA', 'USD', null, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BV', 'AN', 'NOK', null, 'Bouvet Island');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('EH', 'AF', 'MAD', null, 'Western Sahara');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FK', 'SA', 'FKP', null, 'Falkland Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GB', 'EU', 'GBP', null, 'United Kingdom');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GS', 'AN', 'GBP', null, 'South Georgia and the South Sandwich Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HM', 'AN', 'AUD', null, 'Heard Island and McDonald Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IO', 'AS', 'GBP', null, 'British Indian Ocean Territory');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KG', 'AS', 'KGS', null, 'Kyrgyzstan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KP', 'AS', 'KPW', null, 'North Korea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KR', 'AS', 'KRW', null, 'South Korea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LA', 'AS', 'LAK', null, 'Laos');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MO', 'AS', 'MOP', null, 'Macau');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('RU', 'EU', 'RUB', null, 'Russia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SH', 'AF', 'SHP', null, 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SJ', 'EU', 'NOK', null, 'Svalbard & Jan Mayen Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SK', 'EU', 'EUR', null, 'Slovakia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SX', 'NA', 'ANG', null, 'Sint Maarten');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SY', 'AS', 'SYP', null, 'Syrian Arab Republic');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TF', 'AN', 'EUR', null, 'French Southern Territories');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('UM', 'OC', 'USD', null, 'United States Minor Outlying Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VA', 'EU', 'EUR', null, 'Vatican City');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VI', 'NA', 'USD', null, 'United States Virgin Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('EU', 'EU', 'EUR', null, 'Euro Zone');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('YE', 'AS', 'YER', null, 'Yemen');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('WF', 'OC', 'XPF', null, 'Wallis and Futuna');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VN', 'AS', 'VND', null, 'Vietnam');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VE', 'SA', 'VES', null, 'Venezuela');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SS', 'AF', 'SSP', null, 'South Sudan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ES', 'EU', 'EUR', null, 'Spain');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LK', 'AS', 'LKR', null, 'Sri Lanka');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SD', 'AF', 'SDG', null, 'Sudan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SR', 'SA', 'SRD', null, 'Suriname');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SE', 'EU', 'SEK', null, 'Sweden');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CH', 'EU', 'CHF', null, 'Switzerland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TW', 'AS', 'TWD', null, 'Taiwan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TJ', 'AS', 'TJS', null, 'Tajikistan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TZ', 'AF', 'TZS', null, 'Tanzania');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TH', 'AS', 'THB', null, 'Thailand');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TL', 'AS', 'USD', null, 'Timor-Leste');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TG', 'AF', 'XOF', null, 'Togo');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MQ', 'NA', 'EUR', null, 'Martinique');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TK', 'OC', 'NZD', null, 'Tokelau');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TT', 'NA', 'TTD', null, 'Trinidad and Tobago');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TN', 'AF', 'TND', null, 'Tunisia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TR', 'AS', 'TRY', null, 'Turkey');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TM', 'AS', 'TMT', null, 'Turkmenistan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TC', 'NA', 'USD', null, 'Turks and Caicos Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TV', 'OC', 'AUD', null, 'Tuvalu');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('UG', 'AF', 'UGX', null, 'Uganda');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('UA', 'EU', 'UAH', null, 'Ukraine');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AE', 'AS', 'AED', null, 'United Arab Emirates');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('US', 'NA', 'USD', null, 'United States');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('UY', 'SA', 'UYU', null, 'Uruguay');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('UZ', 'AS', 'UZS', null, 'Uzbekistan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VU', 'OC', 'VUV', null, 'Vanuatu');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TO', 'OC', 'TOP', null, 'Tonga');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MH', 'OC', 'USD', null, 'Marshall Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('NA', 'AF', 'NAD', null, 'Namibia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ML', 'AF', 'XOF', null, 'Mali');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CV', 'AF', 'CVE', null, 'Cabo Verde');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KH', 'AS', 'KHR', null, 'Cambodia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CM', 'AF', 'XAF', null, 'Cameroon');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CA', 'NA', 'CAD', null, 'Canada');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KY', 'NA', 'KYD', null, 'Cayman Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CF', 'AF', 'XAF', null, 'Central African Republic');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('TD', 'AF', 'XAF', null, 'Chad');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CL', 'SA', 'CLP', null, 'Chile');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CN', 'AS', 'CNY', null, 'China');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CX', 'AS', 'AUD', null, 'Christmas Island');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CC', 'AS', 'AUD', null, 'Cocos (Keeling) Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CO', 'SA', 'COP', null, 'Colombia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KM', 'AF', 'KMF', null, 'Comoros');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MT', 'EU', 'EUR', null, 'Malta');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CK', 'OC', 'NZD', null, 'Cook Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CR', 'NA', 'CRC', null, 'Costa Rica');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CI', 'AF', 'XOF', null, 'Cote D''Ivoire');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HR', 'EU', 'HRK', null, 'Croatia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CU', 'NA', 'CUP', null, 'Cuba');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CW', 'NA', 'ANG', null, 'Curaçao');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CY', 'AS', 'EUR', null, 'Cyprus');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CZ', 'EU', 'CZK', null, 'Czech Republic');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DK', 'EU', 'DKK', null, 'Denmark');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DJ', 'AF', 'DJF', null, 'Djibouti');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DM', 'NA', 'XCD', null, 'Dominica');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DO', 'NA', 'DOP', null, 'Dominican Republic');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('EC', 'SA', 'USD', null, 'Ecuador');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BI', 'AF', 'BIF', null, 'Burundi');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BF', 'AF', 'XOF', null, 'Burkina Faso');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BG', 'EU', 'BGN', null, 'Bulgaria');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('VG', 'NA', 'USD', null, 'British Virgin Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AX', 'EU', 'EUR', null, 'Åland Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AL', 'EU', 'ALL', null, 'Albania');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DZ', 'AF', 'DZD', null, 'Algeria');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AS', 'OC', 'USD', null, 'American Samoa');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AD', 'EU', 'EUR', null, 'Andorra');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AO', 'AF', 'AOA', null, 'Angola');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AI', 'NA', 'XCD', null, 'Anguilla');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AG', 'NA', 'XCD', null, 'Antigua and Barbuda');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AR', 'SA', 'ARS', null, 'Argentina');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AM', 'AS', 'AMD', null, 'Armenia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AW', 'NA', 'AWG', null, 'Aruba');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AU', 'OC', 'AUD', null, 'Australia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AT', 'EU', 'EUR', null, 'Austria');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('EG', 'AF', 'EGP', null, 'Egypt');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('AZ', 'AS', 'AZN', null, 'Azerbaijan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BH', 'AS', 'BHD', null, 'Bahrain');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BD', 'AS', 'BDT', null, 'Bangladesh');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BB', 'NA', 'BBD', null, 'Barbados');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BY', 'EU', 'BYN', null, 'Belarus');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BE', 'EU', 'EUR', null, 'Belgium');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BZ', 'NA', 'BZD', null, 'Belize');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BJ', 'AF', 'XOF', null, 'Benin');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BM', 'NA', 'BMD', null, 'Bermuda');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BT', 'AS', 'BTN', null, 'Bhutan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BO', 'SA', 'BOB', null, 'Bolivia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BA', 'EU', 'BAM', null, 'Bosnia-Herzegovina');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BW', 'AF', 'BWP', null, 'Botswana');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BR', 'SA', 'BRL', null, 'Brazil');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('BS', 'NA', 'BSD', null, 'Bahamas');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SV', 'NA', 'USD', null, 'El Salvador');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('CD', 'AF', 'CDF', null, 'Congo');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ER', 'AF', 'ERN', null, 'Eritrea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ID', 'AS', 'IDR', null, 'Indonesia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IR', 'AS', 'IRR', null, 'Iran');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IQ', 'AS', 'IQD', null, 'Iraq');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IE', 'EU', 'EUR', null, 'Ireland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IM', 'EU', 'IMP', null, 'Isle of Man');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IL', 'AS', 'ILS', null, 'Israel');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IT', 'EU', 'EUR', null, 'Italy');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('JM', 'NA', 'JMD', null, 'Jamaica');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('JP', 'AS', 'JPY', null, 'Japan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('JE', 'EU', 'JEP', null, 'Jersey');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('JO', 'AS', 'JOD', null, 'Jordan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KZ', 'AS', 'KZT', null, 'Kazakhstan');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KE', 'AF', 'KES', null, 'Kenya');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GQ', 'AF', 'XAF', null, 'Equatorial Guinea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KW', 'AS', 'KWD', null, 'Kuwait');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LV', 'EU', 'EUR', null, 'Latvia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LB', 'AS', 'LBP', null, 'Lebanon');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LS', 'AF', 'LSL', null, 'Lesotho');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LR', 'AF', 'LRD', null, 'Liberia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LY', 'AF', 'LYD', null, 'Libya');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LI', 'EU', 'CHF', null, 'Liechtenstein');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LT', 'EU', 'EUR', null, 'Lithuania');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('LU', 'EU', 'EUR', null, 'Luxembourg');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MG', 'AF', 'MGA', null, 'Madagascar');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MW', 'AF', 'MWK', null, 'Malawi');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MY', 'AS', 'MYR', null, 'Malaysia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('MV', 'AS', 'MVR', null, 'Maldives');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IN', 'AS', 'INR', null, 'India');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('IS', 'EU', 'ISK', null, 'Iceland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('KI', 'OC', 'AUD', null, 'Kiribati');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HK', 'AS', 'HKD', null, 'Hong Kong');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HU', 'EU', 'HUF', null, 'Hungary');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('EE', 'EU', 'EUR', null, 'Estonia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('SZ', 'AF', 'SZL', null, 'Eswatini');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('ET', 'AF', 'ETB', null, 'Ethiopia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FO', 'EU', '---', null, 'Faroe Islands');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FJ', 'OC', 'FJD', null, 'Fiji');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FI', 'EU', 'EUR', null, 'Finland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('FR', 'EU', 'EUR', null, 'France');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GF', 'SA', 'EUR', null, 'French Guiana');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('PF', 'OC', 'XPF', null, 'French Polynesia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GA', 'AF', 'XAF', null, 'Gabon');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GM', 'AF', 'GMD', null, 'Gambia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GE', 'AS', 'GEL', null, 'Georgia');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('DE', 'EU', 'EUR', null, 'Germany');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GT', 'NA', 'GTQ', null, 'Guatemala');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HN', 'NA', 'HNL', null, 'Honduras');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GI', 'EU', 'GIP', null, 'Gibraltar');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GR', 'EU', 'EUR', null, 'Greece');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GL', 'NA', 'DKK', null, 'Greenland');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GD', 'NA', 'XCD', null, 'Grenada');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GP', 'NA', 'EUR', null, 'Guadeloupe');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GU', 'OC', 'USD', null, 'Guam');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GH', 'AF', 'GHS', null, 'Ghana');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GG', 'EU', 'GGP', null, 'Guernsey');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GN', 'AF', 'GNF', null, 'Guinea');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GW', 'AF', 'XOF', null, 'Guinea-Bissau');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('GY', 'SA', 'GYD', null, 'Guyana');
INSERT INTO countries (code, continent_code, currency, investing_id, name) VALUES ('HT', 'NA', 'HTG', null, 'Haiti');