-- INSERT INTO languages (id, code, name, native_name, domain) VALUES (54, 'id', 'Indonesian', 'Bahasa Indonesia');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (53, 'th', 'Thai', 'ไทย', 'th');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (52, 'vi', 'Vietnamese', 'Việtnam', 'vn');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (55, 'zh-hant', 'Chinese (Traditional)', '繁體中文', 'hk');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (6, 'zh-hans', 'Chinese (Simplified)', '简体中文', 'cn');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (18, 'ko', 'Korean', '한국어', 'kr');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (11, 'ja', 'Japanese', '日本語', 'jp');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (2, 'he', 'Hebrew', 'עברית', 'il');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (17, 'fi', 'Finnish', 'Suomi', 'fi');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (13, 'sv', 'Swedish', 'Svenska', 'se');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (14, 'el', 'Greek', 'Ελληνικά', 'gr');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (3, 'ar', 'Arabic', 'العربية', 'sa');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (7,'ru', 'Russian', 'Русский', 'ru');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (15, 'pl', 'Polish', 'Polski', 'pl');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (12, 'pt', 'Portuguese', 'Português', 'pt');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (16, 'nl', 'Dutch', 'Nederlands', 'nl');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (9, 'it', 'Italian', 'Italiano', 'it');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (5, 'fr', 'French', 'Français', 'fr');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (4, 'es', 'Spanish', 'Español', 'es');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (8, 'de', 'German', 'Deutsch', 'de');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (1, 'en', 'English', 'English', 'www');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (58, 'ms', 'Malay', 'Bahasa Melayu', 'ms');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (10, 'tr', 'Turkish', 'Türkçe', 'tr');
INSERT INTO languages (id, code, name, native_name, domain) VALUES (73, 'hi', 'Hindi', 'हिन्दी', 'hi');

INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PE', 'SA', 'PEN', 125, 'Peru');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PH', 'AS', 'PHP', 45, 'Philippines');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PL', 'EU', 'PLN', 53, 'Poland');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PT', 'EU', 'EUR', 38, 'Portugal');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('QA', 'AS', 'QAR', 170, 'Qatar');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('RO', 'EU', 'RON', 100, 'Romania');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('RW', 'AF', 'RWF', 80, 'Rwanda');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('SA', 'AS', 'SAR', 52, 'Saudi Arabia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('RS', 'EU', 'RSD', 238, 'Serbia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('SG', 'AS', 'SGD', 36, 'Singapore');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('SI', 'EU', 'EUR', 112, 'Slovenia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PS', 'AS', 'ILS', 193, 'Palestinian Territory');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('PK', 'AS', 'PKR', 44, 'Pakistan');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MU', 'AF', 'MUR', 188, 'Mauritius');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MX', 'NA', 'MXN', 7, 'Mexico');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MN', 'AS', 'MNT', 139, 'Mongolia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ME', 'EU', 'EUR', 247, 'Montenegro');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MA', 'AF', 'MAD', 105, 'Morocco');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('NL', 'EU', 'EUR', 21, 'Netherlands');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('NZ', 'OC', 'NZD', 43, 'New Zealand');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('NG', 'AF', 'NGN', 20, 'Nigeria');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('NO', 'EU', 'NOK', 60, 'Norway');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('OM', 'AS', 'OMR', 87, 'Oman');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ZA', 'AF', 'ZAR', 110, 'South Africa');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ZM', 'AF', 'ZMW', 84, 'Zambia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ZW', 'AF', 'USD', 75, 'Zimbabwe');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('GB', 'EU', 'GBP', 4, 'United Kingdom');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('KR', 'AS', 'KRW', 11, 'South Korea');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('RU', 'EU', 'RUB', 56, 'Russian Federation');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('SK', 'EU', 'EUR', 90, 'Slovakia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('EU', 'EU', 'EUR', 72, 'Europe');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('VN', 'AS', 'VND', 178, 'Vietnam');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('VE', 'SA', 'VES', 138, 'Venezuela');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ES', 'EU', 'EUR', 26, 'Spain');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('LK', 'AS', 'LKR', 162, 'Sri Lanka');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('SE', 'EU', 'SEK', 9, 'Sweden');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CH', 'EU', 'CHF', 12, 'Switzerland');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('TW', 'AS', 'TWD', 46, 'Taiwan');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('TZ', 'AF', 'TZS', 85, 'Tanzania');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('TH', 'AS', 'THB', 41, 'Thailand');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('TN', 'AF', 'TND', 202, 'Tunisia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('TR', 'AS', 'TRY', 63, 'Turkey');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('UG', 'AF', 'UGX', 123, 'Uganda');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('UA', 'EU', 'UAH', 61, 'Ukraine');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('AE', 'AS', 'AED', 143, 'United Arab Emirates');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('US', 'NA', 'USD', 5, 'United States');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('NA', 'AF', 'NAD', 172, 'Namibia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CA', 'NA', 'CAD', 6, 'Canada');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('KY', 'NA', 'KYD', 232, 'Cayman Islands');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CL', 'SA', 'CLP', 27, 'Chile');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CN', 'AS', 'CNY', 37, 'China');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CO', 'SA', 'COP', 122, 'Colombia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MT', 'EU', 'EUR', 109, 'Malta');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CR', 'NA', 'CRC', 15, 'Costa Rica');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CI', 'AF', 'XOF', 78, 'Cote D''Ivoire');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('HR', 'EU', 'HRK', 113, 'Croatia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CY', 'AS', 'EUR', 107, 'Cyprus');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('CZ', 'EU', 'CZK', 55, 'Czech Republic');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('DK', 'EU', 'DKK', 24, 'Denmark');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('EC', 'SA', 'USD', 121, 'Ecuador');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BG', 'EU', 'BGN', 70, 'Bulgaria');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('AR', 'SA', 'ARS', 29, 'Argentina');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('AU', 'OC', 'AUD', 25, 'Australia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('AT', 'EU', 'EUR', 54, 'Austria');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('EG', 'AF', 'EGP', 59, 'Egypt');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BH', 'AS', 'BHD', 145, 'Bahrain');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BD', 'AS', 'BDT', 47, 'Bangladesh');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BE', 'EU', 'EUR', 34, 'Belgium');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BA', 'EU', 'BAM', 174, 'Bosnia-Herzegovina');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BW', 'AF', 'BWP', 163, 'Botswana');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('BR', 'SA', 'BRL', 32, 'Brazil');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('ID', 'AS', 'IDR', 48, 'Indonesia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IQ', 'AS', 'IQD', 66, 'Iraq');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IE', 'EU', 'EUR', 33, 'Ireland');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IL', 'AS', 'ILS', 23, 'Israel');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IT', 'EU', 'EUR', 10, 'Italy');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('JM', 'NA', 'JMD', 119, 'Jamaica');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('JP', 'AS', 'JPY', 35, 'Japan');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('JO', 'AS', 'JOD', 92, 'Jordan');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('KZ', 'AS', 'KZT', 102, 'Kazakhstan');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('KE', 'AF', 'KES', 57, 'Kenya');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('KW', 'AS', 'KWD', 94, 'Kuwait');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('LV', 'EU', 'EUR', 97, 'Latvia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('LB', 'AS', 'LBP', 68, 'Lebanon');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('LT', 'EU', 'EUR', 96, 'Lithuania');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('LU', 'EU', 'EUR', 103, 'Luxembourg');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MW', 'AF', 'MWK', 111, 'Malawi');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('MY', 'AS', 'MYR', 42, 'Malaysia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IN', 'AS', 'INR', 14, 'India');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('IS', 'EU', 'ISK', 106, 'Iceland');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('HK', 'AS', 'HKD', 39, 'Hong Kong');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('HU', 'EU', 'HUF', 93, 'Hungary');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('EE', 'EU', 'EUR', 89, 'Estonia');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('FI', 'EU', 'EUR', 71, 'Finland');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('FR', 'EU', 'EUR', 22, 'France');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('DE', 'EU', 'EUR', 17, 'Germany');
INSERT INTO countries (code, continent_code, currency, id, name) VALUES ('GR', 'EU', 'EUR', 51, 'Greece');